### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by MythRen** [vulhub/vulhub#11]
项目的 readme 里:

> 本项目中所有环境仅用于测试，不可作为生成环境使用！

我想应该是  `生产` 吧 ? 

另外在 官网首页 https://vulhub.org/ 最下方:

> 编译及启动环境时可能会出现BUG，请提交Issue及时和官方反应。

官方`反映` 吧 ?

**Comment by zjuchenyuan** [comment]
这种非紧要的小问题我觉得不适合作为issue提出，更适合给维护者发个邮件？

## 不要在watch人数很多的repo轻易提issue

请留心这个repo的watch人数，发起一个issue就意味着124个人会收到邮件通知，几个错别字惊动这么多人没必要吧？

**Comment by MythRen** [comment]
嗯, 多谢提醒  🙏
