### ISSUE TITLE
【ecshop】初始化失败

### ISSUE THREAD

**Issue by ech0yg** [vulhub/vulhub#112]
docker创建成功后，进行ecshop初始化，2.7版本成功安装。
3.6安装过程中，数据库和配置文件能够创建成功，提交后提示“内容损坏错误”
![image](https://user-images.githubusercontent.com/45033430/56731765-da2de000-678d-11e9-8907-2314975d5fc7.png)

![image](https://user-images.githubusercontent.com/45033430/56731712-be2a3e80-678d-11e9-9f7d-ee22b4fefeca.png)

![image](https://user-images.githubusercontent.com/45033430/56731097-37289680-678c-11e9-91c1-736e5f40a257.png)

之后访问首页为空：
![image](https://user-images.githubusercontent.com/45033430/56731130-4c9dc080-678c-11e9-90e1-87ee8d763a03.png)

注入漏洞无法复现，提示server超时：
![image](https://user-images.githubusercontent.com/45033430/56731195-79ea6e80-678c-11e9-8128-edd7fc7b81a8.png)

**Comment by phith0n** [comment]
安装完后的确会返回一个错误的数据包，302跳转时地址的端口错了，这个是ecshop本身代码的问题，但不影响安装结果。

访问首页空白是因为本身就是空白。

你无法复现的原因有两个：

1. 数据包发送错误（如缺少一个`\r\n`），导致服务端一直等待你的请求，直到timeout
2. 你使用的是2.7的Payload

我测试没有问题。
