### ISSUE TITLE
docker compose failed in SSTI

### ISSUE THREAD

**Issue by ne0shi** [vulhub/vulhub#113]
sudo docker-compose build
Building flask
Step 1/7 : FROM vulhub/python:3.5
 ---> ea9846919a07
Step 2/7 : MAINTAINER phithon <root@leavesongs.com>
 ---> Using cache
 ---> eea4f3aa880f
Step 3/7 : ADD requirements.txt /tmp/requirements.txt
 ---> Using cache
 ---> 1263bcdb4796
Step 4/7 : RUN mkdir /app     && pip install -U -r /tmp/requirements.txt
 ---> Running in ad7492fa6112
standard_init_linux.go:207: exec user process caused "exec format error"
ERROR: Service 'flask' failed to build: The command '/bin/sh -c mkdir /app     && pip install -U -r /tmp/requirements.txt' returned a non-zero code: 1
shin@shin:~/vulhub-master/flask/ssti$

**Comment by phith0n** [comment]
执行`cat /proc/cpuinfo`看看你计算机的位数与CPU类型。

vulhub大部分环境仅支持在64位Intel架构计算机运行。

**Comment by ne0shi** [comment]
I see, I am using a 32 bit maybe I should upgrade. Thanks man
