### ISSUE TITLE
dns-zone-transfer 启动失败

### ISSUE THREAD

**Issue by sky1561004** [vulhub/vulhub#136]
root@sky-VirtualBox:/home/sky/vulhub-master/dns/dns-zone-transfer# docker-compose up -d
Starting dns-zone-transfer_dns_1 ... error

ERROR: for dns-zone-transfer_dns_1  Cannot start service dns: b'driver failed programming external connectivity on endpoint dns-zone-transfer_dns_1 (5a14dab8b55eb3b77ab223821493ae3639fd320f329a64025ba7724d497ba4e0): Error starting userland proxy: listen tcp 0.0.0.0:53: bind: address already in use'

ERROR: for dns  Cannot start service dns: b'driver failed programming external connectivity on endpoint dns-zone-transfer_dns_1 (5a14dab8b55eb3b77ab223821493ae3639fd320f329a64025ba7724d497ba4e0): Error starting userland proxy: listen tcp 0.0.0.0:53: bind: address already in use'
ERROR: Encountered errors while bringing up the project.
root@sky-VirtualBox:/home/sky/vulhub-master/dns/dns-zone-transfer# 
![image](https://user-images.githubusercontent.com/49974396/64423350-e3826e00-d0d8-11e9-9839-d659d4e527b8.png)

**Comment by phith0n** [comment]
看错误信息就是本地53端口已被占用。

请关闭你本地的DNS服务器，再启动Vulhub对应环境。
