### ISSUE TITLE
vulhub/wordpress/pwnscriptum/ bulid 出错

### ISSUE THREAD

**Issue by RenJunFeng** [vulhub/vulhub#148]
提交issue前，请检查你本地的vulhub是否是最新版，否则可能存在一些由于时间问题导致而今已经修复的bug。

填写如下信息

 - Which environment: 哪个环境出现BUG [e.g. python/ssti]
 - Host OS: 操作系统 [e.g. Ubuntu]
 - OS Version: 操作系统版本 [e.g. 18.04]
 - Docker version: Docker 版本 [e.g. Docker version 18.04.0-ce, build 3d479c0]
 - Compose version: Docker-Compose 版本 [e.g. docker-compose version 1.22.0, build f46880f]
 - Describe your bug: 描述你的Bug，什么情况下出现这个bug

一些关键信息：

 - [ ] 主机是否在中国大陆
 - [ ] 是否重试过仍然出现这个错误

注意，issue仅接受vulhub自身的bug，如：

- 编译时出现bug导致编译失败
- 运行后，环境无法访问
- 环境运行后，按照README中的操作，无法复现漏洞
- README中出现的错误，如错别字、参考链接失效等

不接受：

- 安装docker或docker-compose时出现的bug
- 运行docker、docker-compose时出现的bug
- 拉取/下载vulhub时出现的bug
- 拉取docker镜像因为网络原因导致拉取失败

## 附加信息

请贴出完整错误信息，可以是命令行输出、软件报错信息、截图等。

**注意，请贴出完整错误信息，不要只粘贴错误的最后一行！**
<img width="960" alt="微信图片_20191101110914" src="https://user-images.githubusercontent.com/12624913/67999673-37a06d80-fc98-11e9-955d-a401137d3614.png">

**Comment by phith0n** [comment]
经检查Dockerfile没有任何问题，你需要使用国外VPS编译。

为方便国内用户，我修改了docker-compose.yml，使用已经编译好的Wordpress，避免因为网络问题造成的错误。

另外，之后如果issue填写错误，请按照模板填写信息，信息给予不全，我将直接Close这个issue。

**Comment by RenJunFeng** [comment]
我确实是在国外的VPS上运行，我现在如何操作呀，是需要重新编译然后再运行是吗？

**Comment by phith0n** [comment]
重新执行`docker-compose up -d`即可。

**Comment by RenJunFeng** [comment]
<img width="669" alt="微信截图_20191112153729" src="https://user-images.githubusercontent.com/12624913/68651456-6bb24300-0562-11ea-8cf0-715ed581c652.png">
您好，我直接执行，还是报上面的错呢

**Comment by phith0n** [comment]
……拉取最新的vulhub
