### ISSUE TITLE
vulhub/wordpress/pwnscriptum 运行时，web启动不了

### ISSUE THREAD

**Issue by forgetheart** [vulhub/vulhub#150]
- Which environment: vulhub/wordpress/pwnscriptum
 - Host OS: centos
 - OS Version: CentOS Linux release 7.6.1810 (Core)
 - Docker version: Docker version 1.13.1, build 7f2769b/1.13.1
 - Compose version: docker-compose version 1.18.0, build 8dd22a9
 - Describe your bug: `docker-compose up -d`启动容器时，web并没启动

## 附加信息

![1](https://user-images.githubusercontent.com/22907374/68107386-ac390d80-ff1f-11e9-8870-e15493692375.png)
。

**Comment by phith0n** [comment]
在 https://github.com/vulhub/vulhub/issues/148 里一并处理。

**Comment by phith0n** [comment]
我发现你这个错误和 #148 不同，请执行`docker-compose logs`查看错误信息，复现没有发现你这个问题。

另外，请按照issue模板填写issue，不要删除模板里的信息。
