### ISSUE TITLE
关于 [discuz/wooyun-2010-080723]  php版本问题

### ISSUE THREAD

**Issue by ewan9hu** [vulhub/vulhub#157]
- [discuz/wooyun-2010-080723] 
- 漏洞利用需要用到 register_globals=On 
docker-compose 生成环境 php版本是5.6.36，5.4以后已经删除了这个配置，导致复现不成功
(会不会是我dockers-compose 没有调好php环境0_0)

**Comment by phith0n** [comment]
本漏洞不需要`register_globals =On`。

所有漏洞均使用vulhub上的环境复现，不存在复现时环境与vulhub的环境不同的情况。
