### ISSUE TITLE
weblogic ssrf环境搭建失败

### ISSUE THREAD

**Issue by hjnccbsz** [vulhub/vulhub#171]
提交issue前，请检查你本地的vulhub是否是最新版，否则可能存在一些由于时间问题导致而今已经修复的bug。

填写如下信息

 - Which environment: weblogic/ssrf [e.g. python/ssti]
 - Host OS: Linux kali 4.13.0-kali1-amd64
 - OS Version: SMP Debian 4.13.10-1kali2 (2017-11-08) x86_64 GNU/Linux
 - Docker version:  Docker version 19.03.4, build 9013bf5
 - Compose version: docker-compose version 1.25.0, build 0a186604
 - Describe your bug: 描述你的Bug，什么情况下出现这个bug
      运行docker-compose build的时候在第三步报错，无法建立redis，报错信息如下

root@kali:/usr/local/vulhub-master/weblogic/ssrf# docker-compose build
weblogic uses an image, skipping
Building redis
Step 1/10 : FROM vulhub/cron
 ---> 2cf795262563
Step 2/10 : MAINTAINER phithon <root@leavesongs.com>
 ---> Using cache
 ---> d4c1cf9c8eab
Step 3/10 : RUN set -ex     && yum -y update     && yum -y install gcc-c++ tcl wget
 ---> Running in 9c5ab6f07d1b
ERROR: Service 'redis' failed to build: The command '/bin/sh -c set -ex     && yum -y update     && yum -y install gcc-c++ tcl wget' returned a non-zero code: 139

 - [是 ] 主机是否在中国大陆
 - [是 ] 是否重试过仍然出现这个错误

注意，issue仅接受vulhub自身的bug，如：

- 编译时出现bug导致编译失败
- 运行后，环境无法访问
- 环境运行后，按照README中的操作，无法复现漏洞
- README中出现的错误，如错别字、参考链接失效等

注意：关于环境搭建成功，但复现漏洞不成功的情况，我可能不会测试并回复issue，因为我在搭建环境的时候均已测试成功。建议此类issue作者自行测试并寻找错误原因，如果找到原因的确是vulhub的问题（比如某种情况没考虑到），则再创建issue。

不接受：

- 安装docker或docker-compose时出现的bug
- 运行docker、docker-compose时出现的bug
- 拉取/下载vulhub时出现的bug
- 拉取docker镜像因为网络原因导致拉取失败

## 附加信息

请贴出完整错误信息，可以是命令行输出、软件报错信息、截图等。

**注意，请贴出完整错误信息，不要只粘贴错误的最后一行！**

**Comment by phith0n** [comment]
看起来是yum安装软件的时候出现的网络错误，和Vulhub代码本身无关，建议在境外VPS上再次进行测试看看。
