### ISSUE TITLE
Dockerfile?

### ISSUE THREAD

**Issue by fqlq** [vulhub/vulhub#187]
The Dockerfile of vulhub/weblogic was not found on the github or dockerhub. Could you please provide the Dockerfile documents?

**Comment by phith0n** [comment]
Weblogic is not open-source software, I don't have a standard way to create a Dockerfile. 

Some suggested Docker images here:

- <https://container-registry.oracle.com/pls/apex/f?p=113:4:109451761356314::NO:RP,4:P4_REPOSITORY,AI_REPOSITORY,P4_REPOSITORY_NAME,AI_REPOSITORY_NAME:5,5,Oracle%20Fusion%20Middleware%20Infrastructure,Oracle%20Fusion%20Middleware%20Infrastructure&cs=3-CydvV9IG61smkmddVxnR28HRds0QMIAESVhWbXwCXpmu-GPkd02FeHDGoP0mpeq2EOjl-DlZvfC1FOpB8YU2g>
- https://github.com/henryzzq/ubuntu_weblogic1036_domain

Please use it at your own risks.
