### ISSUE TITLE
update

### ISSUE THREAD

**Issue by Tukali** [vulhub/vulhub#196]
If vulhub is updated with a new vulnerability environment, how do I update the installed vulhub? Do I need to reinstall it

**Comment by phith0n** [comment]
Follow these steps:

Firstly, shut down the existing containers. If you haven't run any container, just ignore it:

```
cd /path/to/environment
docker-compose down -v
```

Then, download the newest Vulhub:

```
# download through Git
git pull

# or download the zip archive, just overwrite the exists codes
wget https://github.com/vulhub/vulhub/archive/master.zip
unzip master.zip
```

Thirdly, launch any new "vulnerability environment" that you like:

```
cd /path/to/new/environment
docker-compose up -d
```
