### ISSUE TITLE
drupal-7600 无法复现

### ISSUE THREAD

**Issue by vskunkka** [vulhub/vulhub#199]
![image](https://user-images.githubusercontent.com/62331240/82894197-c6ead680-9f84-11ea-812e-674d68a204a7.png)

**Comment by phith0n** [comment]
你这连返回包都没有，说明访问不到drupal。

无法复现的问题（没有错误日志），如果你没找到具体原因，我这边也没法处理，因为我发布的时候都测试过，且截图是测试的结果。

**Comment by phith0n** [comment]
如果有找到具体原因，可以重新打开这个issue再跟我反馈。

**Comment by vskunkka** [comment]
![image](https://user-images.githubusercontent.com/62331240/83324064-2d2d6d00-a295-11ea-8088-190f8df2c4ed.png)
http://8.129.43.146:8080/user/register
没办法复现
