### ISSUE TITLE
cgi httpproxy build失败

### ISSUE THREAD

**Issue by laohuan12138** [vulhub/vulhub#204]
在复现cgi httpproxy漏洞时，build失败，错误代码`Service 'php' failed to build: The command '/bin/sh -c set -ex   && apt-get update && apt-get install -y zip unzip     && wget -qO- https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer     && cd /var/www/html     && composer install   && apt-get purge -y --auto-remove wget zip unzip' returned a non-zero code: 1`

**Comment by phith0n** [comment]
build失败通常是本地互联网的问题，可以选择使用海外的VPS进行漏洞测试。

不过我更新了一下这个环境，现在不需要本地build环境了。你需要重写拉取一下最新的vulhub和镜像：

```
docker-compose pull
docker-compose up -d
```
