### ISSUE TITLE
本地环境搭建失败，中国大陆服务器

### ISSUE THREAD

**Issue by Tsunami-Song** [vulhub/vulhub#214]
Unpacking git-man (1:2.1.4-2.1+deb8u10) ...
Selecting previously unselected package git.
Preparing to unpack .../git_1%3a2.1.4-2.1+deb8u10_amd64.deb ...
Unpacking git (1:2.1.4-2.1+deb8u10) ...
Setting up libcurl3-gnutls:amd64 (7.38.0-4+deb8u16) ...
Setting up liberror-perl (0.17-1.1) ...
Setting up git-man (1:2.1.4-2.1+deb8u10) ...
Setting up git (1:2.1.4-2.1+deb8u10) ...
Processing triggers for libc-bin (2.19-18+deb8u7) ...
+ cd /var/www/html/
+ curl -sSL https://getcomposer.org/installer                                                                                                                                                       
+ php                                                                                                                                                                                               
curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104

**Comment by phith0n** [comment]
请按照Bug Report模板填写issue：

https://github.com/vulhub/vulhub/issues/new?template=bug-report.md
