### ISSUE TITLE
404 not found while downloading containers 

### ISSUE THREAD

**Issue by pentestguy** [vulhub/vulhub#218]
I am using docker on windows environment and try to download it using kitematic but it's shows 
**(HTTP code 404) no such image - no such image: vulhub/struts2:latest: No such image: vulhub/struts2:lates**

**Comment by phith0n** [comment]
Which vulnerability did you test? 

Please use the form below to describe your question:

 - Which environment: [e.g. python/ssti]
 - Host OS: [e.g. Ubuntu]
 - OS Version: [e.g. 18.04]
 - Docker version: [e.g. Docker version 18.04.0-ce, build 3d479c0]
 - Compose version: [e.g. docker-compose version 1.22.0, build f46880f]
 - Describe your bug, include the full error message, traceback or screenshots:
