### ISSUE TITLE
树莓派docker-compose: standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by Jerry-zhuang** [vulhub/vulhub#235]
树莓派docker-compose: standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by phith0n** [comment]
注意阅读[README](https://github.com/vulhub/vulhub/blob/master/README.zh-cn.md)：

> ## Notice
> 注意事项：
> 
> 为防止出现权限错误，最好使用root用户执行docker和docker-compose命令
> **docker部分镜像不支持在ARM等架构的机器上运行**
