### ISSUE TITLE
Docker-compose在下载镜像时一直在downloading卡住不动

### ISSUE THREAD

**Issue by 3397043602** [vulhub/vulhub#247]
Pulling tomcat (vulhub/tomcat:8.0)...
8.0: Pulling from vulhub/tomcat
6d827a3ef358: Pull completeMB/51.44MBB1: Downloading [====================================>              ]  13.67MB/18.61MB2: Download complete
0ab260573986: Download complete
b7c48cee0b2b: Download complete7MB/77.89MBc: Waiting
e4b9c85c3e06: Download complete
ee3dc5d1e4c7: Download complete
e101174ccdbd: Download complete
b4ba120532be: Download complete4MB/9.937MB5: Waiting
一直卡住

**Comment by phith0n** [comment]
说明你的网络较慢，建议使用海外VPS进行测试。

**Comment by 3397043602** [comment]
> 说明你的网络较慢，建议使用海外VPS进行测试。

不是，我前面很快的，到最后就定住不动了，不是网络问题

**Comment by phith0n** [comment]
> > 说明你的网络较慢，建议使用海外VPS进行测试。
> 
> 不是，我前面很快的，到最后就定住不动了，不是网络问题

这个问题你只能寻求docker官方的帮助了。Vulhub所有镜像储存在dockerhub中，且没有任何对镜像网络上的额外处理，如果你拉不下来镜像，可以网上查找一下和docker相关的解决方法。

**Comment by 3397043602** [comment]
> > > 说明你的网络较慢，建议使用海外VPS进行测试。
> > 
> > 
> > 不是，我前面很快的，到最后就定住不动了，不是网络问题
> 
> 这个问题你只能寻求docker官方的帮助了。Vulhub所有镜像储存在dockerhub中，且没有任何对镜像网络上的额外处理，如果你拉不下来镜像，可以网上查找一下和docker相关的解决方法。

害，我已经找了不知道多少解决办法了，就是没有我的那种

**Comment by phith0n** [comment]
最快的解决方法就是找一台海外机器进行测试。

**Comment by plxj6666** [comment]
> 最快的解决方法就是找一台海外机器进行测试。

谢谢，刚才解决了，参考blog:https://blog.csdn.net/m0_65933139/article/details/130181525  修改DNS
