### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by x-cz75** [vulhub/vulhub#274]
我在执行docker-compose up -d时，报如下错误，尝试多种措施后依然报错。
![Snipaste_2021-05-11_15-39-19](https://user-images.githubusercontent.com/84007478/117777419-29f57c00-b26f-11eb-81fc-3fad9b1ae436.png)
![Snipaste_2021-05-11_15-39-56](https://user-images.githubusercontent.com/84007478/117777429-2cf06c80-b26f-11eb-870f-eecfbf64d2e9.png)

**Comment by phith0n** [comment]
你好，docker和docker-compose软件使用相关的报错可以在相应的文档和Github中进行查看，Vulhub项目无法解决这类问题：

- [docker](https://docs.docker.com/)
- [docker-compose](https://docs.docker.com/compose/)
