### ISSUE TITLE
一直拉取

### ISSUE THREAD

**Issue by owlachaoshen** [vulhub/vulhub#278]
半小时了 一直卡在这不动 删除重装好几次了都是这样 从docker直接拉取很快没问题 应该不是网络问题 请问是什么原因
![1621666177(1)](https://user-images.githubusercontent.com/24353635/119217618-f2f45580-bb0d-11eb-88ad-0786df8d942e.jpg)

**Comment by phith0n** [comment]
Vulhub所有的镜像全部保存在dockerhub中，没有任何云端服务。如果你遇到了无法拉取镜像的问题，可以提交给Docker官方解决，或者使用加速器。

**Comment by phith0n** [comment]
另外抛开这些问题不说，我本地测试也没有复现你的问题，应该也不是dockerhub的问题。

![image](https://user-images.githubusercontent.com/5711185/119217865-b6295e00-bb0f-11eb-8ec3-8ee013e3d949.png)
