### ISSUE TITLE
Nginx 不安全的配置 CRLF 注入8080端口无法访问

### ISSUE THREAD

**Issue by hzh2020** [vulhub/vulhub#353]
- Host OS: 操作系统  `CentOS7`
 - OS Version: 操作系统版本  `3.10.0-514.el7.x86_64`
 - Docker version: Docker 版本 `20.10.8`
 - Compose version: Docker-Compose 版本` 5.0.0 `
 - Describe your bug: 正常使用`docker-compose`启动，显示启动成功。容器一共映射了3个端口。其中一个端口`8080`访问不到，另外两个端口可以访问到；
 - 主机在本地虚拟机 
 - 重试过仍然出现这个错误
 - vulhub 20220513号下载的版本

dock容器启动状态
![图片](https://user-images.githubusercontent.com/61353686/168211444-530fc15d-d37e-4100-8511-406f28597422.png)

宿主机端口监听状态
![图片](https://user-images.githubusercontent.com/61353686/168211524-787adb2f-34ec-42ab-ab19-6da7fc93842d.png)

宿主机防火墙状态
![图片](https://user-images.githubusercontent.com/61353686/168211666-a5978e72-c563-4eed-8442-37f2c6be0db5.png)

访问8080端口，链接不到端口；访问链接的是http://127.0.0.1:8080，
截图是自己跳转的
![图片](https://user-images.githubusercontent.com/61353686/168211251-3b1ab51a-1220-4631-b126-b86d4caca8bb.png)

访问8081端口，可以正常访问
![图片](https://user-images.githubusercontent.com/61353686/168211208-e72035dc-e160-420c-ba1e-8c390c66b512.png)

访问8082端口，可以正常访问
![图片](https://user-images.githubusercontent.com/61353686/168211363-17d6b7a2-cc92-45cf-b6c8-4a0974db2070.png)

重启过docker服务，重启过系统，都没能解决这个问题；
希望能解答。十分感谢！

**Comment by neargle** [comment]
FIXED, 试试 https://github.com/neargle/vulhub/tree/fix-issue-353。

**Comment by hzh2020** [comment]
> FIXED, 试试 https://github.com/neargle/vulhub/tree/fix-issue-353 。

安装试了一遍，访问`8080`端口出现如下错误提示：
火狐：
![图片](https://user-images.githubusercontent.com/61353686/169543915-69084c81-b797-478b-b932-9a0cc19ecdc8.png)
Chrome：
![图片](https://user-images.githubusercontent.com/61353686/169543997-1e1fa7d0-082f-4bf2-b5e8-f8a7e982975a.png)

同样访问`8081`  `8082` 端口没有问题

**Comment by neargle** [comment]
> > FIXED, 试试 https://github.com/neargle/vulhub/tree/fix-issue-353 。
> 
> 安装试了一遍，访问`8080`端口出现如下错误提示： 火狐： ![图片](https://user-images.githubusercontent.com/61353686/169543915-69084c81-b797-478b-b932-9a0cc19ecdc8.png) Chrome： ![图片](https://user-images.githubusercontent.com/61353686/169543997-1e1fa7d0-082f-4bf2-b5e8-f8a7e982975a.png)
> 
> 同样访问`8081` `8082` 端口没有问题

少年 学习一下原理哈 重定向是正常的 header头已经注入了

**Comment by hzh2020** [comment]
> > > FIXED, 试试 https://github.com/neargle/vulhub/tree/fix-issue-353 。
> > 
> > 
> 
> 少年 学习一下原理哈 重定向是正常的 header头已经注入了

嗯嗯，之前没看到靶场的配置文件，看过之后明白了；

	location / {
		return 302 http://$host:$server_port$uri;
	}
就是说访问`8080`端口的根目录，会`302`跳转到指定的地址；
哈哈，这下明白一些了；
感谢你的解答！

**Comment by neargle** [comment]
🤙🤙🤙

**Comment by zrquan** [comment]
@neargle 貌似补充 `$server_port` 就可以解决这个 issue 了，请问将配置中的 https 改成 http 是出于什么考虑呢，改了之后有点脱离现实场景（http 跳转 https 倒是比较常规的处理，README 也是这样说明的）而且会导致循环重定向。

**Comment by neargle** [comment]
> @neargle 貌似补充 `$server_port` 就可以解决这个 issue 了，请问将配置中的 https 改成 http 是出于什么考虑呢，改了之后有点脱离现实场景（http 跳转 https 倒是比较常规的处理，README 也是这样说明的）而且会导致循环重定向。

确实，使用 http 虽然依然可以复现漏洞，http 跳转到 https 这个场景需求更常见。但这个fix 有点久远了，我当时的目的应该只是想修复这个环境，让他可以 work，确实记不住这里的修改是为什么了。

这个 commit 本身的目的还是修复 bug，让环境重新可以正常使用，最终确实达成了这个目的。

或许需要一个新的 pull request 把他修改成https，只要漏洞是如目前这样可以复现的。

**Comment by neargle** [comment]
> @neargle 貌似补充 `$server_port` 就可以解决这个 issue 了，请问将配置中的 https 改成 http 是出于什么考虑呢，改了之后有点脱离现实场景（http 跳转 https 倒是比较常规的处理，README 也是这样说明的）而且会导致循环重定向。

哦，收回前言，我觉得这个修改是必须的，你可以测试一下。我突然发现，这个环境我们的配置文件里没有配置 listen ssl，如果 https 访问原端口应该会出现 ERR_SSL_PROTOCOL_ERROR，建议你测试一下看看，并反馈一下结果。

**Comment by zrquan** [comment]
> 哦，收回前言，我觉得这个修改是必须的，你可以测试一下。我发现，这个环境我们的配置文件里没有配置 listen ssl，如果 https 访问原端口应该会出现 ERR_SSL_PROTOCOL_ERROR，建议你测试一下看看，并反馈一下结果。
>
跳转后的 https 请求确实会 ERR_SSL_PROTOCOL_ERROR，但是不影响漏洞复现。

**Comment by neargle** [comment]
@zrquan 是 curl 测的吗？还是 burp？可以发个截图哈

**Comment by zrquan** [comment]
> @zrquan 是 curl 测的吗？还是 burp？可以发个截图哈

用 HackBar 测的

![Screenshot_20240513_153920](https://github.com/vulhub/vulhub/assets/33086594/4146cba1-3287-47ca-8298-c1918f4fc651)

![image](https://github.com/vulhub/vulhub/assets/33086594/f0f1659a-1391-4105-adb1-98f22f4bf7ce)

总结下我这边测试的情况是，跳转到 https 的话就 ERR_SSL_PROTOCOL_ERROR，跳转 http 的话就 ERR_TOO_MANY_REDIRECTS，两者都不影响漏洞复现，但前者不会在浏览器触发多个重定向请求而且对得上 README 的描述

![Screenshot_20240513_154146](https://github.com/vulhub/vulhub/assets/33086594/41c8861a-d614-41a8-90af-38d77a837c4c)

**Comment by neargle** [comment]
@zrquan 了解，修改回 https 我也是支持的。emm... 或许最佳的方式是加一个 nginx site配置，设置类似`listen 443 ssl`，然后跳转到这个 tsl 端口。这样既不会 ERR_SSL_PROTOCOL_ERROR 也符合 readme 描述的场景。
