### ISSUE TITLE
[Document] Discord link in readme.md is invalid.

### ISSUE THREAD

**Issue by neargle** [vulhub/vulhub#354]
https://discord.com/invite/GhMB3Z

![image](https://user-images.githubusercontent.com/7868679/169047027-0387ce3d-b16d-4735-b4b2-1bef71736fd4.png)

**Comment by LV6LV** [comment]
The link is bad again... Can someone post a new one please?

**Comment by phith0n** [comment]
Although I've updated the Discord link, it not a really active group.

https://discord.gg/bQCpZEK
