### ISSUE TITLE
Proposal: Need Dockerfile

### ISSUE THREAD

**Issue by tylzh97** [vulhub/vulhub#361]
When we reproduce vulnerabilities, not only need to attack the target, but also need to analyze the vulnerability code!!! So the construction process of vulnerability environment is very important. Providing Dockerfile instead of pulling docker image by docker-compose can facilitate us to build the environment. Can you provide Dockerfile in each CVE directory?

--------------

当我们重现漏洞时，不仅需要攻击目标，还需要分析漏洞代码!!!所以脆弱环境的构建过程非常重要。提供 Dockerfile 而不是通过 docker-compose 拉取 docker 镜像，可以方便我们构建环境。你能在每个CVE目录中提供Dockerfile吗？

**Comment by phith0n** [comment]
你可以的，所有dockerfile都可以在base/目录下找到。

**Comment by tylzh97** [comment]
您好，我已经收到了您的邮件，我将尽快给您恢复。-李政浩 Lizhenghao
