### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by xiaozhaha** [vulhub/vulhub#362]
vulhub是最新版的。
m1pro的虚拟机，虚拟机系统是 ubuntu 20.04.0 arm64。
docker-compose up -d 报错如下。
![image](https://user-images.githubusercontent.com/48639007/176987972-20be0cfd-c2be-4de2-a377-07e53f37d16e.png)

我没找到在哪里更改 “exec /bin/sh:” 这些的文件。
docker-compose.yml 这个文件内没有这些内容。
以前win的ubuntu虚拟机没问题的，现在不知道什么情况。
求p牛解答。

**Comment by phith0n** [comment]
你好，[README](https://github.com/vulhub/vulhub#notice)中有说明，部分环境无法在RAM机器运行：

> ## Notice
> - To prevent permission errors, it is best to use the root user to execute the docker and docker-compose commands.
> - Some docker images do not support running on ARM machines.
