### ISSUE TITLE
docker-compose 启动失败

### ISSUE THREAD

**Issue by leishigege** [vulhub/vulhub#376]
主机：macbook air M1 版本. macOS Monterey 12.5
虚拟机软件：Parallel Desktop 版本 18.0.2 (53077)
虚拟主机操作系统：Kali linux
操作步骤：
  1:sudo apt install docker.io 方式安装docker
  2:按照官网doc（https://vulhub.org/#/docs/run/）进行vulhub 安装并使用docker-compose up -d启动

<img width="947" alt="image" src="https://user-images.githubusercontent.com/61509858/195094944-b88228ba-7af8-4c6b-8785-790ff47f94aa.png">

ps: curl -s https://get.docker.com/ | sh 方式安装docker失败
**sources.list:**
  
#中科大
deb http://mirrors.ustc.edu.cn/kali kali-rolling main non-free contrib
deb-src http://mirrors.ustc.edu.cn/kali kali-rolling main non-free contrib
#阿里云
deb http://mirrors.aliyun.com/kali kali-rolling main non-free contrib
deb-src http://mirrors.aliyun.com/kali kali-rolling main non-free contrib
#清华大学
deb http://mirrors.tuna.tsinghua.edu.cn/kali kali-rolling main contrib non-free
deb-src https://mirrors.tuna.tsinghua.edu.cn/kali kali-rolling main contrib non-free
#浙大
deb http://mirrors.zju.edu.cn/kali kali-rolling main contrib non-free
deb-src http://mirrors.zju.edu.cn/kali kali-rolling main contrib non-free
#东软大学
deb http://mirrors.neusoft.edu.cn/kali kali-rolling/main non-free contrib
deb-src http://mirrors.neusoft.edu.cn/kali kali-rolling/main non-free contrib
#官方源
deb http://http.kali.org/kali kali-rolling main non-free contrib
deb-src http://http.kali.org/kali kali-rolling main non-free contrib

**sources.list end**
<img width="932" alt="image" src="https://user-images.githubusercontent.com/61509858/195116091-49c9ea95-bb46-446a-a7fa-e03ccb04fb50.png">
望指导，谢谢！

**Comment by phith0n** [comment]
可以执行`docker-compose logs`看一下错误信息是什么。

**Comment by leishigege** [comment]
> 可以执行`docker-compose logs`看一下错误信息是什么。

![Uploading image.png…]()

**Comment by leishigege** [comment]
<img width="422" alt="image" src="https://user-images.githubusercontent.com/61509858/195123532-fa2050cf-3959-459d-9b3e-ee89f37c912d.png">

**Comment by phith0n** [comment]
Vulhub环境只支持x86架构CPU运行。

**Comment by leishigege** [comment]
> Vulhub环境只支持x86架构CPU运行。

ok 3q

**Comment by cynicalight** [comment]
有什么办法可以在arm架构下使用vulhub吗
