### ISSUE TITLE
漏洞环境启动失败

### ISSUE THREAD

**Issue by eako-eako** [vulhub/vulhub#398]
用docker-compose up -d启动环境后，docker ps -a查看容器一直是exited状态，docker logs报错exec /usr/bin/java错误，请问怎么解决
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/67313352/204066748-05d3d19c-3df5-44b9-be11-f2aaf1bf2183.png">

**Comment by phith0n** [comment]
请在x86架构机器上使用Vulhub，如果有问题，按照issue模板提交issue：<https://github.com/vulhub/vulhub/issues/new?assignees=&labels=&template=bug-report.md>。
