### ISSUE TITLE
苹果M1芯片启动项目时exec 格式错误

### ISSUE THREAD

**Issue by czybryant** [vulhub/vulhub#457]
本地的vulhub是否是最新版。

 - Which environment: docker compose 
 - Host OS: 操作系统 Ubuntu 
 - OS Version: 操作系统版本 22.04
 - Docker version: Docker 版本 Docker version 24.0.5, build ced0996
 - Compose version: Docker-Compose 版本 Docker Compose version v2.20.2
 - Describe your bug: 当使用docker compose启动时出现如下提示
 [+] Running 3/0
 ✔ Network ssti_default                                                                                                                               Created0.0s 
 ✔ Container ssti-web-1                                                                                                                               Created0.0s 
 ! web The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s 
Attaching to ssti-web-1
ssti-web-1  | exec /bin/sh: exec format error
ssti-web-1 exited with code 1

当我在 ARM 架构的系统（ Apple M 系列芯片组）上处理项目时，导致“exec 用户进程导致：exec 格式错误”。Docker 将 Apple M1 Pro 平台检测为“linux/arm64/v8”。

 - [ 是] 主机是否在中国大陆
 - [ 是] 是否重试过仍然出现这个错误

## 附加信息
<img width="960" alt="image" src="https://github.com/vulhub/vulhub/assets/31762516/d39ef347-8b2c-46c8-a2f2-acb5eca43384">

**Comment by phith0n** [comment]
你好，参见README中的说明，Vulhub暂不支持非x86架构运行：

> Vulhub does not support running on machines with non-x86 architecture such as ARM for now.
