### ISSUE TITLE
docker-compose build 失败， kali 最新 docker （18.03.1-ce）

### ISSUE THREAD

**Issue by jinyu00** [vulhub/vulhub#46]
```
root@kali:~/vulhub/weblogic/ssrf# docker-compose build
Building redis
Step 1/10 : FROM vulhub/cron
 ---> 2cf795262563
Step 2/10 : MAINTAINER phithon <root@leavesongs.com>
 ---> Using cache
 ---> e43ed2cc9cfe
Step 3/10 : RUN set -ex     && yum -y update     && yum -y install gcc-c++ tcl wget
 ---> Running in ba1ae39768a8
ERROR: Service 'redis' failed to build: The command '/bin/sh -c set -ex     && yum -y update     && yum -y install gcc-c++ tcl wget' returned a non-zero code: 139
root@kali:~/vulhub/weblogic/ssrf# docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.10.3
 Git commit:   9ee9f40
 Built:        Wed, 11 Jul 2018 20:15:24 +1000
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.3
  Git commit:   9ee9f40
  Built:        Wed Jul 11 10:15:24 2018
  OS/Arch:      linux/amd64
  Experimental: false
root@kali:~/vulhub/weblogic/ssrf# 

```

**Comment by phith0n** [comment]
测试没有出现错误。

![image](https://user-images.githubusercontent.com/5711185/44618274-9d7bb300-a8a5-11e8-99f0-23fc4debdb57.png)

你发布的这条日志：

```
ERROR: Service 'redis' failed to build: The command '/bin/sh -c set -ex     && yum -y update     && yum -y install gcc-c++ tcl wget' returned a non-zero code: 139
```

没有任何错误详情，请截取这段日志前面的部分。

**Comment by jinyu00** [comment]
上面就是所有信息了

**Comment by phith0n** [comment]
如果是`set -ex     && yum -y update     && yum -y install gcc-c++ tcl wget`出现错误，那就是网络原因。

**Comment by phith0n** [comment]
之后我会将镜像编译好，尽量不让大家在复现漏洞的时候编译软件，避免网络原因造成的错误，尽情期待~

**Comment by jinyu00** [comment]
好的， 网络应该没有问题， 我现在在 ubuntu 16.04 上可以 build 成功

**Comment by phith0n** [comment]
网络问题是影响因素，网络慢的时候编译可能超时导致出错，但不代表每次编译都会超时。

我执行的语句是`set -ex && yum -y update && yum -y install gcc-c++ tcl wget`，就是CentOS下最简单的安装软件的命令，不可能存在错误。

如果你能在kali下稳定复现这个错误，那可能性只有两个：

1. debian系统的问题
2. debian下docker的兼容性问题

所以建议还是用ubuntu进行使用。

**Comment by Xiaomuchen0715** [comment]
和楼上一样的问题
<img width="1101" alt="屏幕快照 2019-06-08 下午8 51 55" src="https://user-images.githubusercontent.com/26465093/59147519-4e1b0380-8a2f-11e9-8771-8869a9e6e5f4.png">

**Comment by phith0n** [comment]
> 和楼上一样的问题
> <img alt="屏幕快照 2019-06-08 下午8 51 55" width="1101" src="https://user-images.githubusercontent.com/26465093/59147519-4e1b0380-8a2f-11e9-8771-8869a9e6e5f4.png">

日志里已经明确说明了“unable to resolve host address 'download.redis.io'”，DNS解析失败，请挂全局代理后再进行尝试。

**Comment by MyDynasty** [comment]
好像是跟内核版本有关系，只有VPS3（最低版本内核）可以直接build环境
VPS1：Linux iZ5i5v6gggg4veZ 5.4.0-kali3-amd64 #1 SMP Debian 5.4.13-1kali1 (2020-01-20) x86_64 GNU/Linux
VPS2：Linux vultr.guest 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
VPS3：Linux VM-0-7-debian 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2 (2017-06-12) x86_64 GNU/Linux


```
docker-compose build
weblogic uses an image, skipping
Building redis
Step 1/10 : FROM vulhub/cron
 ---> 2cf795262563
Step 2/10 : MAINTAINER phithon <root@leavesongs.com>
 ---> Using cache
 ---> 78c78dd14dea
Step 3/10 : RUN set -ex     && yum -y update     && yum -y install gcc-c++ tcl wget
 ---> Running in ba1ae39768a8
ERROR: Service 'redis' failed to build: The command '/bin/sh -c set -ex     && yum -y update     && yum -y install gcc-c++ tcl wget' returned a non-zero code: 139
```


**解决方法是把Dockerfile文件中RUN替换为CMD后，即可正常build环境**
**解决方法是把Dockerfile文件中RUN替换为CMD后，即可正常build环境**
**解决方法是把Dockerfile文件中RUN替换为CMD后，即可正常build环境**
