### ISSUE TITLE
Include `Dockerfile` in the repo

### ISSUE THREAD

**Issue by za** [vulhub/vulhub#462]
Hi there,

I am new to this container things. When we created [images](https://hub.docker.com/r/vulhub/django/tags), how we create the image? Are we using `Dockerfile`? 

I don't see any `Dockerfile` in the repo and only see `docker-compose.yml` in the repo.

**Comment by phith0n** [comment]
Hi @za

You can find most of the Dockerfiles in the [base](https://github.com/vulhub/vulhub/tree/master/base) folder.

**Comment by za** [comment]
Ah, yes. I haven't go through that folder yet. Thanks @phith0n 

Maybe we should put this information somewhere. Any idea?

I am closing/resolving this issue now.

**Comment by phith0n** [comment]
> Ah, yes. I haven't go through that folder yet. Thanks @phith0n
> 
> Maybe we should put this information somewhere. Any idea?
> 
> I am closing/resolving this issue now.

Sure. I think we can provide such information in the README~
