### ISSUE TITLE
运行ecshop的安装界面失败

### ISSUE THREAD

**Issue by star-xzh** [vulhub/vulhub#509]
提交issue前，请检查你本地的vulhub是否是最新版，否则可能存在一些由于时间问题导致而今已经修复的bug。

填写如下信息

 - Which environment: ecshop\xianzhi-2017-02-82239600
 - Host OS: Windows11
 - OS Version: 10.0.22000 Build 22000
 - Docker version: Docker version 24.0.7, build afdd53b
 - Compose version: Docker Compose version v2.23.3-desktop.2
 - Describe your bug: 
 根据readeMe的步骤运行了ecshop的漏洞环境 发现连接进入localhost:8080提示
 {"res":"false","rsp":"\u7f3a\u5c11\u5fc5\u8981\u7684\u53c2\u6570"}
 - [ 是]
 - [ 是] 
<img width="692" alt="{5BF82BEE-F0E6-4e6b-A741-0814F7C4EE38}" src="https://github.com/vulhub/vulhub/assets/79817022/067753a3-1061-4cf3-90e0-40e051cfef85">

**Comment by phith0n** [comment]
完全没有进入安装页面，直接出现这个错误吗？还是在安装过程中出现错误？

**Comment by star-xzh** [comment]
> 完全没有进入安装页面，直接出现这个错误吗？还是在安装过程中出现错误？

直接进入就出现了这个错误

**Comment by phith0n** [comment]
请使用其他浏览器或者隐身模式试一下吧。

查看ecshop代码可见这个错误的原因是你直接提交了POST请求，但请求包中没有包含数据库相关配置：

![image](https://github.com/vulhub/vulhub/assets/5711185/d3b71692-758d-49d5-ad2f-1a90d7e010b8)

**Comment by star-xzh** [comment]
> 请使用其他浏览器或者隐身模式试一下吧。
> 
> 查看ecshop代码可见这个错误的原因是你直接提交了POST请求，但请求包中没有包含数据库相关配置：
> 
> ![image](https://private-user-images.githubusercontent.com/5711185/315924760-d3b71692-758d-49d5-ad2f-1a90d7e010b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTM2MTgsIm5iZiI6MTcxMTA5MzMxOCwicGF0aCI6Ii81NzExMTg1LzMxNTkyNDc2MC1kM2I3MTY5Mi03NThkLTQ5ZDUtYWQyZi0xYTkwZDdlMDEwYjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjJUMDc0MTU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzEyNjkyN2U5NmRjY2MyNTFhODI2YmU3ZTVkNWFhMDJjOTcxOTAyMmE1YzVmNTFhMTcxNmE1N2FkZTU4ZGJhNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SGhG2h2j9VIY9G1MM7SSO-0Bvs_YIufW5E7HRXlk8JI)

非常感谢 我使用了chrome浏览器可以进行访问了 但是在edge上还是无法访问
<img width="519" alt="{65B0D682-ABF9-48f9-95CD-06A33ED1EE13}" src="https://github.com/vulhub/vulhub/assets/79817022/12c19363-4ab1-47cc-b72d-d1b7185afd86">
<img width="585" alt="{7FAC6A3A-3C18-4977-A1F4-4A77F17C7A57}" src="https://github.com/vulhub/vulhub/assets/79817022/6eb8e277-e562-4747-b95e-862ff7406dce">
我看到在网络中 使用的是get方法但是还是显示缺少必要参数

**Comment by phith0n** [comment]
可以自行排除一下插件的原因吧。请求方法不一定需要是POST，如果是GET，但是进入到了auto_index.php这个代码逻辑中就会出现这个错误。

进入的原因是这条if语句：

![image](https://github.com/vulhub/vulhub/assets/5711185/72210808-705e-4a2a-bb01-45aac431de99)

可能是你的什么插件或者代理给你加了一些额外的参数，如`data=xx`，自行排除原因，与vulhub无关了。
