### ISSUE TITLE
MINIO zh-cn.md文档细节问题

### ISSUE THREAD

**Issue by qfmy1024** [vulhub/vulhub#526]
![image](https://github.com/vulhub/vulhub/assets/76994810/da7d6290-b556-46bf-8681-cf6929f305fd)
![image](https://github.com/vulhub/vulhub/assets/76994810/f83007de-a5b4-42eb-9db6-9cee37d5f15d)
中文文档细节问题，望采纳，我说咋找不到MINIO_SECRET_KEY，中英文MD文档开头提到的也是MINIO_SECRET_KEY哦，不知道是不是我误解了。

**Comment by phith0n** [comment]
已修改，感谢！
