### ISSUE TITLE
镜像总是拉不下来，怎么回事？

### ISSUE THREAD

**Issue by gps1949** [vulhub/vulhub#538]
下载最新的版本，尝试了好几个服务器，都拉不下来镜像
![image](https://github.com/vulhub/vulhub/assets/62601891/dcb1d4f2-a7ab-40c7-ba35-40607fa79871)

**Comment by phith0n** [comment]
你好，网络相关的问题Vulhub无法处理，需要自行解决docker hub官方与中国大陆的网络问题。
