### ISSUE TITLE
能不能直接通过代理编译环境 比如 SOCKS5代理

### ISSUE THREAD

**Issue by woadmin** [vulhub/vulhub#72]
填写如下信息

 - Which environment: 哪个环境出现BUG [e.g. python/ssti]
 - Host OS: 操作系统 [e.g. Ubuntu]
 - OS Version: 操作系统版本 [e.g. 18.04]
 - Docker version: Docker 版本 [e.g. Docker version 18.04.0-ce, build 3d479c0]
 - Compose version: Docker-Compose 版本 [e.g. docker-compose version 1.22.0, build f46880f]
 - Describe your bug: 描述你的Bug，什么情况下出现这个bug

一些关键信息：

 - [x] 主机是否在中国大陆
 - [x] 是否重试过仍然出现这个错误

注意，issue仅接受vulhub自身的bug，如：

- 编译时出现bug导致编译失败
- 运行后，环境无法访问
- 环境运行后，按照README中的操作，无法复现漏洞
- README中出现的错误，如错别字、参考链接失效等

不接受：

- 安装docker或docker-compose时出现的bug
- 运行docker、docker-compose时出现的bug
- 拉取/下载vulhub时出现的bug
- 拉取docker镜像因为网络原因导致拉取失败

## 附加信息

请贴出完整错误信息，可以是命令行输出、软件报错信息、截图等。

**注意，请贴出完整错误信息，不要只粘贴错误的最后一行！**

**Comment by woadmin** [comment]
对不起，第一次发信息，没想到发成这样了~~~

**Comment by younglinuxer** [comment]
设置全局代理 可以拉取镜像

**Comment by mullvadcat** [comment]
sudo pip install shadowsocks
sudo proxychains4 -q /bin/bash
即可

**Comment by phith0n** [comment]
几年过去了，我已尽可能把所有编译的操作全部放在基础镜像里，大部分环境不需要在启动镜像的时候进行编译。如果还有类似的情况，麻烦再开issue告诉我。
