### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by Mehran** [vulhub/vulhub#76]
I used `docker run -it -p 2222:22 --rm vulhub/libssh:0.8.1 `

when trying to connect it freezes 

![0](https://user-images.githubusercontent.com/23736885/47279626-35b0c280-d5df-11e8-8654-6a9048680503.jpg)

**Comment by phith0n** [comment]
Hi,
 
I used to come up with this problem, but it doesn't be reproduced every time. So if you know how to solve the problem, please update the issue.
