### ISSUE TITLE
PHP环境 XML外部实体注入漏洞（XXE）无法正常使用

### ISSUE THREAD

**Issue by i-liberty** [vulhub/vulhub#81]
版本为最新
centos7
内核版本 3.10.0-862.9.1.el7.x86_64 #1 SMP Mon Jul 16 16:29:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Docker version 1.13.1, build dded712/1.13.1
docker-compose version 1.22.0, build f46880f
PHP环境 XML外部实体注入漏洞（XXE）编译过程无报错  无法正常使用 访问 index.php 显示 Not Found 其他脚本也是   删除环境重新编译也是一样

**Comment by i-liberty** [comment]
进入容器内部之后 ls -all 显示没权限访问
ls: cannot open directory '.': Permission denied

docker-compose top web  显示：
php_xxe_web_1
UID    PID    PPID   C   STIME   TTY     TIME                    CMD                
------------------------------------------------------------------------------------
root   3404   3388   0   17:08   ?     00:00:00   php -S 0.0.0.0:80 -t /var/www/html

**Comment by phith0n** [comment]
应该是路径在映射到容器里后，容器内的进程没权限读取文件导致的错误。

应该是开了SELinux导致的？或者看看你`php/php_xxe`这个目录下所有文件的权限，如果不是755可以修改一下。

**Comment by i-liberty** [comment]
果然是开启了SELinux导致的  多谢帮助  解决了 
解决办法：关闭SELinux之后 重启
