### ISSUE TITLE
Gogs image not available

### ISSUE THREAD

**Issue by MinatoTW** [vulhub/vulhub#87]
Hi,
The image for the gogs container isn't available. I'll be grateful if you can push it.
Thanks!

**Comment by phith0n** [comment]
Thanks, I have pushed it.

In addition, the image is here: [https://github.com/vulhub/vulhub/blob/master/base/gogs/0.11.66/Dockerfile](https://github.com/vulhub/vulhub/blob/master/base/gogs/0.11.66/Dockerfile), just inherited from gogs/gogs.
