### ISSUE TITLE
vulhub/cron 的docker镜像 存在 Exited (139) 的错误，无法新建容器。

### ISSUE THREAD

**Issue by upgradeb** [vulhub/vulhub#99]
vulhub/cron 的docker镜像 存在 Exited (139) 的错误，无法新建容器。

**Comment by phith0n** [comment]
请按照模板填写issue，以便确认错误原因：

https://github.com/vulhub/vulhub/issues/new?template=bug-report.md

**Comment by phith0n** [comment]
另外，很多镜像是不能单独使用的，请在具体漏洞目录下运行`docker-compose up -d`来运行漏洞环境，如果用`docker run`来运行镜像，很多时候是无法正常运行的，因为参数不对。
